/* This file automatically generated by configure.  */

extern void *reallocarray(void *, size_t, size_t);
extern size_t strlcat(char *, const char *, size_t);
extern size_t strlcpy(char *, const char *, size_t);
