/* generated by awk */
#ifdef E
E(  1, "EGENERIC unknown error")
E(  2, "EFAULT")
E(  3, "EBADF bad file descriptor")
E(  4, "EINVAL")
E(  5, "ENOSYS unsupported")
E(  6, "ERANGE")
E(  7, "ENOMEM")
E(  8, "ENOENT")
E(  9, "ENOTEMPTY")
E( 10, "EACCES")
E( 11, "EMFILE all file descriptors taken")
E( 12, "ECONNRESET")
E(200, "EISDIR")
E(201, "ENAMETOOLONG")
#endif
