#!/bin/sh
set -eu

# ensure that we're in the repo root
if [ ! -d .git ]; then
	echo please cd to the repo\'s main directory
	exit
fi

export PREFIX="$(pwd)/toolchain/prefix/"
export PATH="$(pwd)/toolchain/prefix/bin/:$PATH"
BUILDDIR="$(pwd)/toolchain/binutils-build/"
SYSROOT="$(pwd)/sysroot/"
mkdir -p $PREFIX
mkdir -p $BUILDDIR

cd $BUILDDIR

../binutils/configure \
	--target=x86_64-camellia \
	--prefix="$PREFIX" \
	--with-sysroot \
	--disable-nls \
	--disable-werror
make -j4
make install
