#!/bin/sh
set -eu

# ensure that we're in the repo root
if [ ! -d .git ]; then
	echo please cd to the repo\'s main directory
	exit
fi

export PREFIX="$(pwd)/toolchain/prefix/"
export PATH="$(pwd)/toolchain/prefix/bin/:$PATH"
BUILDDIR="$(pwd)/toolchain/gcc-build/"
SYSROOT="$(pwd)/sysroot/"
mkdir -p $PREFIX
mkdir -p $BUILDDIR

cd $BUILDDIR

../gcc/configure \
	--target=x86_64-camellia \
	--prefix="$PREFIX" \
	--with-sysroot="$SYSROOT" \
	--enable-languages=c,c++ \
	--enable-default-pie \
	--disable-nls \
	--disable-gcov \
	--disable-werror
make -j4 all-gcc
make -j4 all-target-libgcc
make install-gcc
make install-target-libgcc
